---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: example
spec:
  payload: IP
  matches:
    - match:
      sourceSelector:
        app: firewall
      route:
        - destination:
          destinationSelector:
            app: nsm-server
    - match:
      route:
        - destination:
          destinationSelector:
            app: firewall
